name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check EditorConfig configuration
        run: test -f .editorconfig

      - name: Check adherence to EditorConfig
        uses: greut/eclint-action@v0

  typos:
    name: Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Search for misspellings
        uses: crate-ci/typos@master

  completed:
    name: Quality-Done # Used as a required workflow name
    runs-on: ubuntu-latest
    needs:
      - editorconfig
      - typos
    steps:
      - run: echo 'completed'
